using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexusOps.WorkflowOrchestrator.Migrations
{
    /// <inheritdoc />
    /// <remarks>
    /// <see cref="OrderInvestigation.OrderInvestigationDbContext"/> deliberately shares its
    /// <c>InboxState</c>/<c>OutboxState</c>/<c>OutboxMessage</c> tables with
    /// <c>OrderActionDbContext</c> rather than owning a private copy (008-order-investigation-outbox
    /// research.md Decision 4) -- normally, this migration would then be a no-op, since
    /// <c>OrderActionDbContext</c>'s own migration (feature 006) already creates them. It is written
    /// with <c>CREATE TABLE/INDEX IF NOT EXISTS</c> instead, so that <c>OrderInvestigationDbContext</c>
    /// does not silently depend on <c>OrderActionDbContext</c>'s migration having run first, or on the
    /// <c>OrderAction</c> folder continuing to exist at all: per this project's own domain-pluggability
    /// principle (Constitution V), documented everywhere as "delete the folder and its one
    /// registration call", `OrderAction` really can be deleted, and applying only this context's
    /// migrations against a fresh database must not leave the investigation saga's own outbox
    /// tables missing -- the exact failure this feature exists to fix, reintroduced at the schema
    /// level instead of the timing level.
    /// </remarks>
    public partial class AddTransactionalOutbox : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "InboxState" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "MessageId" uuid NOT NULL,
                    "ConsumerId" uuid NOT NULL,
                    "LockId" uuid NOT NULL,
                    "RowVersion" bytea,
                    "Received" timestamp with time zone NOT NULL,
                    "ReceiveCount" integer NOT NULL,
                    "ExpirationTime" timestamp with time zone,
                    "Consumed" timestamp with time zone,
                    "Delivered" timestamp with time zone,
                    "LastSequenceNumber" bigint,
                    CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
                    CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "OutboxState" (
                    "OutboxId" uuid NOT NULL,
                    "LockId" uuid NOT NULL,
                    "RowVersion" bytea,
                    "Created" timestamp with time zone NOT NULL,
                    "Delivered" timestamp with time zone,
                    "LastSequenceNumber" bigint,
                    CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "OutboxMessage" (
                    "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "EnqueueTime" timestamp with time zone,
                    "SentTime" timestamp with time zone NOT NULL,
                    "Headers" text,
                    "Properties" text,
                    "InboxMessageId" uuid,
                    "InboxConsumerId" uuid,
                    "OutboxId" uuid,
                    "MessageId" uuid NOT NULL,
                    "ContentType" character varying(256) NOT NULL,
                    "MessageType" text NOT NULL,
                    "Body" text NOT NULL,
                    "ConversationId" uuid,
                    "CorrelationId" uuid,
                    "InitiatorId" uuid,
                    "RequestId" uuid,
                    "SourceAddress" character varying(256),
                    "DestinationAddress" character varying(256),
                    "ResponseAddress" character varying(256),
                    "FaultAddress" character varying(256),
                    "ExpirationTime" timestamp with time zone,
                    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber"),
                    CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId" FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES "InboxState" ("MessageId", "ConsumerId"),
                    CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES "OutboxState" ("OutboxId")
                );
                """);

            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_InboxState_Delivered" ON "InboxState" ("Delivered");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");""");
            migrationBuilder.Sql("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");""");
            migrationBuilder.Sql("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_OutboxId_SequenceNumber" ON "OutboxMessage" ("OutboxId", "SequenceNumber");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_OutboxState_Created" ON "OutboxState" ("Created");""");
        }

        /// <inheritdoc />
        /// <remarks>
        /// Deliberately does not drop these tables: they are shared with
        /// <c>OrderActionDbContext</c>, which may still depend on them even if
        /// <c>OrderInvestigationDbContext</c>'s own migrations are rolled back. This migration's
        /// contract is "ensure these tables exist," not "own their lifecycle" -- symmetric with how
        /// <c>Up()</c> never assumes it was the one that created them either.
        /// </remarks>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
